### ISSUE TITLE
"Generating Unlimited Bookshelves patch" section is unclear and possibly redundant

### ISSUE THREAD

**Issue by bvdzag** [dreadflopp/dreads_modlist_patches#16] opened 2020-05-03 18:52 UTC
The Unlimited Bookshelves patch section contains several redundancies and errors, all after the "After closing SSEEdit..." header.
1) Guide calls for using the "Create new mod..." function to create a patch mod with the SSEEdit output in Overwrite, but then asks user to move the ESP from Overwrite into the "Unlimited_Bookshelves_Patch_Generator_Output" mod they created earlier. This will be impossible if the directions are followed by the letter, as the ESP will already have been moved to the patch mod.
2) The bullet under point (2) refers to FNIS SE generated files, but FNIS is no longer used in this branch.

These errors are likely from a failed commit merge with the original S.T.E.P. core list and should be an easy fix.

**Comment by dreadflopp** [comment] 2020-05-03 21:04
Thanks, a failed commit or sloppy cut and paste was the cause of this. It is fixed now.

**Closed as completed by dreadflopp** 2020-05-03 21:04 UTC
